### ISSUE TITLE
4.12.0 breaks `fs.createWriteStream`

### ISSUE THREAD

**Issue by blimmer** [streamich/memfs#1067]
Consider this simple test:

```js
const { Volume } = require('memfs');

describe('doit', () => {
  it('works', () => {
    const memfs = Volume.fromJSON({
      '/tmp': '',
    });
    memfs.createWriteStream('/tmp/hello.txt').write('world');
  })
})
```

4.12.0 started breaking tests with this error:

```shell
 /tmp/memfs-bug   main ●  npx jest doit.test.js

 RUNS  ./doit.test.js
node:events:505
    throw err; // Unhandled 'error' event
    ^

Error: Unhandled error. (Error: ENOTDIR: not a directory, open '/tmp/hello.txt'
    at createError (/private/tmp/memfs-bug/node_modules/memfs/src/node/util.ts:145:17)
    at Volume.openFile (/private/tmp/memfs-bug/node_modules/memfs/src/volume.ts:760:54)
    at Volume.openBase (/private/tmp/memfs-bug/node_modules/memfs/src/volume.ts:776:23)
    at Immediate._onImmediate (/private/tmp/memfs-bug/node_modules/memfs/src/volume.ts:578:25)
    at processImmediate (node:internal/timers:478:21) {
  code: 'ENOTDIR',
  path: '/tmp/hello.txt'
})
    at Volume.WriteStream.emit (node:events:503:17)
    at Volume.WriteStream.<anonymous> (/private/tmp/memfs-bug/node_modules/memfs/src/volume.ts:2459:14)
    at Immediate.<anonymous> (/private/tmp/memfs-bug/node_modules/memfs/src/volume.ts:580:9)
    at processImmediate (node:internal/timers:478:21) {
  code: 'ERR_UNHANDLED_ERROR',
  context: Error: ENOTDIR: not a directory, open '/tmp/hello.txt'
      at createError (/private/tmp/memfs-bug/node_modules/memfs/src/node/util.ts:145:17)
      at Volume.openFile (/private/tmp/memfs-bug/node_modules/memfs/src/volume.ts:760:54)
      at Volume.openBase (/private/tmp/memfs-bug/node_modules/memfs/src/volume.ts:776:23)
      at Immediate._onImmediate (/private/tmp/memfs-bug/node_modules/memfs/src/volume.ts:578:25)
      at processImmediate (node:internal/timers:478:21) {
    code: 'ENOTDIR',
    path: '/tmp/hello.txt'
  }
}

Node.js v20.10.0
```

Whereas this works with 4.11.2:

```shell
 /tmp/memfs-bug   main ●  npx jest doit.test.js
 PASS  ./doit.test.js
  doit
    ✓ works (1 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.084 s, estimated 1 s
Ran all test suites matching /doit.test.js/i.
```

**Comment by G-Rath** [comment]
@BadIdeaException any chance you could have a look at this?

**Comment by BadIdeaException** [comment]
Correct me if I'm wrong, but as far as I can see, this is intended behavior. 
```
const memfs = Volume.fromJSON({
    '/tmp': '',
});
```
This creates an (empty) **file** `/tmp`. A subsequent try to create `/tmp/hello.txt` is therefore _supposed_ to fail with ENOTDIR. It's functionally equivalent to:
```
fs.writeFileSync('/tmp', '');
fs.writeFileSync('/tmp/hello.txt', 'world');
```
This will result in ENOTDIR in the standard Node fs module, as well.

If this worked previously, that was a bug. (This sort of thing has been an issue before, see #1049.)

**Comment by blimmer** [comment]
Ah, interesting callout. It looks like I've been relying on that buggy behavior in the past. It looks like the proper way to create an empty directory with the `.fromJSON` interface is to pass `null`: https://github.com/streamich/memfs/issues/48.

Thanks for your time looking into this! I'll close this issue now.
