### ISSUE TITLE
Error using it with util.promisify

### ISSUE THREAD

**Issue by thiagodp** [streamich/memfs#111]
I'm trying to use it with Node's [promisify](https://nodejs.org/dist/latest/docs/api/util.html#util_util_promisify_original)...

```javascript
const fs = require( 'memfs' ); // Works with require( 'fs' );
const util = require( 'util' );

( async function() {
	const writeFileAsync = util.promisify( fs.writeFile );
	const readFileAsync = util.promisify( fs.readFile );
	try {
		await writeFileAsync( 'foo.txt', 'bar' );
		const data = await readFileAsync( 'foo.txt' );
		console.log( data.toString() ); // bar
	} catch ( err ) {
		console.log( err );
	}	
}() );
```

but I'm getting the following errors:
```bash
Error: ENOENT: no such file or directory, open 'foo.txt'
    at createError (node_modules\memfs\lib\volume.js:105:17)
    at throwError (node_modules\memfs\lib\volume.js:114:11)
    at Volume.openFile (node_modules\memfs\lib\volume.js:755:17)
    at Volume.openBase (node_modules\memfs\lib\volume.js:765:25)
    at Volume.writeFileBase (node_modules\memfs\lib\volume.js:987:23)
    at Immediate.<anonymous> (node_modules\memfs\lib\volume.js:623:39)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5) code: 'ENOENT'
```

The same code works with node's `fs`. Am I doing something wrong?

**Comment by streamich** [comment]
Try using `/foo.txt` file path. Does the path `process.cwd() + '/foo.txt'` exist in your `memfs` volume.

See docs on relative path: https://github.com/streamich/memfs/blob/master/docs/relative-paths.md

**Comment by thiagodp** [comment]
Thanks @streamich , `vol.mkdirpSync( process.cwd() );` did the trick for me.

This is the full script for those with the same problem:
```js
import { fs, vol } from 'memfs';
import { promisify } from 'util';
import { join } from 'path';

( async function() {

	const writeFileAsync = promisify( fs.writeFile );
	const readFileAsync = promisify( fs.readFile );
	
	vol.mkdirpSync( process.cwd() ); // <=- needed

	try {
		await writeFileAsync( 'foo.txt', 'bar' );
		const data = await readFileAsync( 'foo.txt' );
		console.log( data.toString() );
	} catch ( err ) {
		console.log( err );
	}
	
}() );
```
