### ISSUE TITLE
Cannot read property 'createChild' of null

### ISSUE THREAD

**Issue by haroldo-ok** [streamich/memfs#12]
I'm trying to do a simple test:

	const memfs = require('memfs');
	memfs.fs.writeFileSync('/watson.json', JSON.stringify({
		"ocorrencia_id": 9001
	}));

And, instead of writing things to the file, I'm getting this error:

	TypeError: Cannot read property 'createChild' of null
		at Volume.createLink (C:\Temp\teste-watson\watson-orchestrator\node_modules\memfs\lib\volume.js:382:22)
		at Volume.openFile (C:\Temp\teste-watson\watson-orchestrator\node_modules\memfs\lib\volume.js:641:29)
		at Volume.openBase (C:\Temp\teste-watson\watson-orchestrator\node_modules\memfs\lib\volume.js:649:25)
		at Volume.writeFileBase (C:\Temp\teste-watson\watson-orchestrator\node_modules\memfs\lib\volume.js:878:23)
		at Volume.writeFileSync (C:\Temp\teste-watson\watson-orchestrator\node_modules\memfs\lib\volume.js:903:14)
		at client.query.then.res (C:\Temp\teste-watson\watson-orchestrator\populate\populate.js:37:12)
		at process._tickCallback (internal/process/next_tick.js:109:7)

In fact, all of the examples are giving off this error.

**Comment by streamich** [comment]
The issue is with Windows paths, pls try versin `2.0.8`

    npm install --save memfs@2.0.8

**Comment by haroldo-ok** [comment]
Thanks; I already solved my original problem in a different way, but I will remember this detail next time I use memfs.
