### ISSUE TITLE
fs.existsSync throw when file not found

### ISSUE THREAD

**Issue by sapegin** [streamich/memfs#19]
```js
const { fs } = require('memfs')
fs.existsSync('pizza')
```

Expected result:

```
false
```

Actual result:

```
Error: ENOENT: no such file or directory, stat 'pizza'
    at createError (/Users/sapegin/Dropbox/Projects/_Repos/mrm-core/node_modules/memfs/lib/volume.js:95:17)
    at throwError (/Users/sapegin/Dropbox/Projects/_Repos/mrm-core/node_modules/memfs/lib/volume.js:104:11)
    at Volume.statBase (/Users/sapegin/Dropbox/Projects/_Repos/mrm-core/node_modules/memfs/lib/volume.js:1066:13)
    at Volume.existsBase (/Users/sapegin/Dropbox/Projects/_Repos/mrm-core/node_modules/memfs/lib/volume.js:1123:23)
    at Volume.existsSync (/Users/sapegin/Dropbox/Projects/_Repos/mrm-core/node_modules/memfs/lib/volume.js:1126:21)
    at repl:1:4
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
```

**Comment by streamich** [comment]
Thanks, merged your PR.

Also added #21 

Released under `memfs@2.2.0`:

    npm install --save memfs@2.2.0

Also, FYI, `exists` and `existsSync` are actually deprecated by Node.js

**Comment by sapegin** [comment]
Thanks!

[existsSync](https://nodejs.org/api/fs.html#fs_fs_existssync_path) was undeprecated a long time ago ;-)

**Comment by streamich** [comment]
@sapegin thanks, good to know

**Comment by streamich** [comment]
Did some changes in #22, use version `2.3.0` instead.
