### ISSUE TITLE
Incompatible with graceful-fs

### ISSUE THREAD

**Issue by sapegin** [streamich/memfs#25]
I’m trying to make it work with [graceful-fs](https://github.com/isaacs/node-graceful-fs). And it tries to access `fs.ReadStream.prototype`:

https://github.com/isaacs/node-graceful-fs/blob/65cf80d1fd3413b823c16c626c1e7c326452bee5/graceful-fs.js#L165-L166

which doesn’t exist on memfs:

```
> const fs = require('fs');
undefined
> fs.ReadStream.prototype
ReadStream {
  open: [Function],
  _read: [Function],
  _destroy: [Function],
  close: [Function] }
> const memfs = require('memfs');
undefined
> memfs.fs.ReadStream.prototype
undefined
```

I can make it work by doing this change in `index.ts`:

```diff
-    fs.WriteStream = (volume as any).WriteStream.bind(null, vol);
+    fs.WriteStream = (volume as any).WriteStream;
-    fs.ReadStream = (volume as any).ReadStream.bind(null, vol);
+    fs.ReadStream = (volume as any).ReadStream;
```

But I assume it would break other things (though all tests are passing) otherwise you won’t do that.

**Comment by streamich** [comment]
I refactored it such that now they should have constructors. Try version `2.4.0`.

**Comment by vjpr** [comment]
@streamich `graceful-fs` not working for me...

See test repo here: https://github.com/vjpr/memfs-issue-graceful-fs

- Patch with `fs-monkey`.
- Creates a file.
- Tries to read it.

Gets this error:

```
babel-node .
fs.js:519
    binding.fstat(fd);
            ^

TypeError: fd must be a file descriptor
    at tryStatSync (fs.js:519:13)
    at Object.fs.readFileSync (fs.js:555:3)
    at Object.<anonymous> (/Users/Vaughan/dev-scratch/memfs-graceful-fs/index.js:27:14)
    at Module._compile (module.js:612:30)
    at loader (/Users/Vaughan/nvm/versions/node/v8.8.1/pnpm-global/1/node_modules/.registry.npmjs.org/babel-register/6.26.0/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Vaughan/nvm/versions/node/v8.8.1/pnpm-global/1/node_modules/.registry.npmjs.org/babel-register/6.26.0/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
```

**Comment by streamich** [comment]
Works for me, I get:

```
<Buffer 7b 7d>
```

Are you on Windows by any chance?

**Comment by vjpr** [comment]
Nope. macOS Sierra Node 8.1.1.

**Comment by vjpr** [comment]
Seems to be a node@8 issue.

```
nvm exec 6.5 babel-node .
Running node v6.5.0 (npm v4.2.0)
<Buffer 7b 7d>
```

```
nvm exec 8 babel-node .
Running node v8.8.1 (npm v5.5.1)
fs.js:519
    binding.fstat(fd);
            ^

TypeError: fd must be a file descriptor
    at tryStatSync (fs.js:519:13)
    at Object.fs.readFileSync (fs.js:555:3)
    at Object.<anonymous> (/Users/Vaughan/dev-scratch/memfs-graceful-fs/index.js:27:14)
    at Module._compile (module.js:612:30)
    at loader (/Users/Vaughan/nvm/versions/node/v8.8.1/pnpm-global/1/node_modules/.registry.npmjs.org/babel-register/6.26.0/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Vaughan/nvm/versions/node/v8.8.1/pnpm-global/1/node_modules/.registry.npmjs.org/babel-register/6.26.0/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
```

**Comment by streamich** [comment]
Yes, worked for me using node 7, switched to Node 8, get the same error.

**Comment by streamich** [comment]
https://github.com/nodejs/node/blame/e509db8c564a660231cc09afef3d900f58201afc/lib/fs.js#L570

**Comment by vjpr** [comment]
```
const a = require('graceful-fs').openSync('/app/lerna.json', 'r', 0o666);

Error {
    code: 'ENOENT',
    errno: -2,
    path: '/app/lerna.json',
    syscall: 'open',
    message: 'ENOENT: no such file or directory, open \'/app/lerna.json\'',
  }
```

**Comment by streamich** [comment]
@vjpr what does that mean?

**Comment by vjpr** [comment]
```
require('graceful-fs').openSync('/app/lerna.json', 'r', 0o666)
// fails with ENOENT
require('fs').openSync('/something/that/exists/on/disk', 'r', 0o666)
// 12
const res = require('fs').openSync('/app/lerna.json', 'r', 0o666)
// 4294967295
require('graceful-fs').readFileSync(res)
//  'fd must be a file descriptor',
```

Ah hang on, maybe `graceful-fs` is not being patched by `fs-monkey`, and its just not able to find the file...
