### ISSUE TITLE
Extract tgz file saved in memfs directory to another memfs directory

### ISSUE THREAD

**Issue by WinstonN** [streamich/memfs#483]
Hi, I want to extract a tgz file (which I fetched from S3 and stored in a memfs directory) to another directory stored in the same memfs director

I am using node10 on AWS Lambda

I am getting the error:
```
2019-12-22T03:01:35.780Z	ad1242c0-7ee9-471d-ae04-13478ba3624e	INFO	{ Error: ENOENT: no such file or directory, stat '/tmp/ramdisk/tmp/file.tgz'
    at Object.statSync (fs.js:855:3)
    at extractFileSync (/var/task/node_modules/tar/lib/extract.js:68:19)
    at Object.module.exports (/var/task/node_modules/tar/lib/extract.js:35:33)
    at /var/task/src/global/run.js:214:21
    at Immediate._onImmediate (/var/task/node_modules/memfs/lib/volume.js:657:17)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/tmp/ramdisk/tmp/file.tgz' }
``` 

The file saved correctly, I check it's size
![image](https://user-images.githubusercontent.com/1143789/71316609-2aa13d00-24d7-11ea-9a8c-d3d6ef506ca8.png)

The code I am using is
```
tar.x({
      file: `${ramDisk}/tmp/${fileName}`,
      cwd: `${ramDisk}`,
      sync: true
  })
```

Can you please help me in the right direction? I'm stuck :(

**Comment by WinstonN** [comment]
nvm, this issue helped me solve my problem https://github.com/streamich/fs-monkey/issues/139
