### ISSUE TITLE
Handling fs.constants.O_DIRECTORY flag

### ISSUE THREAD

**Issue by corwin-of-amber** [streamich/memfs#494]
In Node.js, it is possible to open a directory with `fs.open` or `fs.openSync`, specifying read access and optionally the flag `fs.constants.O_DIRECTORY`.
The effect of the flag is only that Node.js will raise `ENOTDIR` if the file is not a directory.

```js
> fd = fs.openSync("/tmp/a", fs.constants.O_RDONLY)
29
> fd = fs.openSync("/tmp/a", fs.constants.O_RDONLY | fs.constants.O_DIRECTORY)
Thrown:
Error: ENOTDIR: not a directory, open '/tmp/a'
    at Object.openSync (fs.js:440:3) {
  errno: -20,
  syscall: 'open',
  code: 'ENOTDIR',
  path: '/tmp/a'
}
> fs.openSync('/', fs.constants.O_RDONLY)
30
> fs.openSync('/', fs.constants.O_RDONLY | fs.constants.O_DIRECTORY)
31
```

In `memfs`, the flag is ignored when opening a file and rejected when attempting to open a directory (`openLink` thinks the requested access is not read-only).
```js
> m.openSync('/', fs.constants.O_RDONLY)
openLink true 0 0
2147483646
> m.openSync('/', fs.constants.O_RDONLY | fs.constants.O_DIRECTORY)
Thrown:
Error: EISDIR: illegal operation on a directory, open
    at createError (node_modules/memfs/lib/volume.js:131:17)
    at Volume.openLink (node_modules/memfs/lib/volume.js:774:19)
    at Volume.openFile (node_modules/memfs/lib/volume.js:806:25)
    at Volume.openBase (node_modules/memfs/lib/volume.js:811:25)
    at Volume.openSync (/Users/corwin/var/workspace/Web.OS.Shell/node_modules/memfs/lib/volume.js:822:21) {
  code: 'EISDIR'
}
```

**Comment by corwin-of-amber** [comment]
The issue has been patched in [this fork](https://github.com/torch2424/memfs/commit/aed9a61c9f88f38f741f8275f743eb2c38298edb), although not completely. I will try to make a PR based on that.

**Comment by streamich** [comment]
@corwin-of-amber thanks!

**Comment by corwin-of-amber** [comment]
Extremely welcome 😄
