### ISSUE TITLE
BUG:  utimesSync doesn't work on directories, but it should

### ISSUE THREAD

**Issue by williamstein** [streamich/memfs#864]
```js
~/cowasm/packages/wasi-js$ node
Welcome to Node.js v19.0.0.
Type ".help" for more information.
> memfs = require('memfs');0;
0
> memfs.vol.fromJSON({'/a/b':'this is b'}, '/');
undefined
> memfs.vol.readdirSync('/a')
[ 'b' ]
> memfs.vol.utimesSync('/a',new Date(), new Date())
Uncaught Error: EISDIR: illegal operation on a directory, open '/a'
    at createError (/Users/wstein/build/cocalc/src/data/projects/2c9318d1-4f8b-4910-8da7-68a965514c95/cowasm/packages/wasi-js/node_modules/memfs/lib/volume.js:128:17)
    at Volume.openLink (/Users/wstein/build/cocalc/src/data/projects/2c9318d1-4f8b-4910-8da7-68a965514c95/cowasm/packages/wasi-js/node_modules/memfs/lib/volume.js:814:23)
    at Volume.openFile (/Users/wstein/build/cocalc/src/data/projects/2c9318d1-4f8b-4910-8da7-68a965514c95/cowasm/packages/wasi-js/node_modules/memfs/lib/volume.js:853:25)
    at Volume.openBase (/Users/wstein/build/cocalc/src/data/projects/2c9318d1-4f8b-4910-8da7-68a965514c95/cowasm/packages/wasi-js/node_modules/memfs/lib/volume.js:858:25)
    at Volume.openSync (/Users/wstein/build/cocalc/src/data/projects/2c9318d1-4f8b-4910-8da7-68a965514c95/cowasm/packages/wasi-js/node_modules/memfs/lib/volume.js:869:21)
    at Volume.utimesBase (/Users/wstein/build/cocalc/src/data/projects/2c9318d1-4f8b-4910-8da7-68a965514c95/cowasm/packages/wasi-js/node_modules/memfs/lib/volume.js:1538:23)
    at Volume.utimesSync (/Users/wstein/build/cocalc/src/data/projects/2c9318d1-4f8b-4910-8da7-68a965514c95/cowasm/packages/wasi-js/node_modules/memfs/lib/volume.js:1547:14) {
  code: 'EISDIR'
}
> 

```

Using the normal filesystem, utimesSync works fine:

```js
/tmp$ mkdir a
/tmp$ node
Welcome to Node.js v19.0.0.
Type ".help" for more information.
> require('fs').utimesSync('a', new Date(), new Date())
undefined
> 
```

**Comment by williamstein** [comment]
Sorry, I see this is a dup of #391
