### ISSUE TITLE
Broken in browser when used with vite

### ISSUE THREAD

**Issue by abhishiv** [streamich/memfs#917]
```
  import {vol, fs} from 'memfs'
  vol.fromJSON(json, "/app");

```

```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at node.js:11:19
    at node.js:32:5
    at ../../node_modules/memfs/lib/node.js (node.js:297:1)
    at __require (chunk-VX4GZB4L.js?v=167728fa:3:50)
    at ../../node_modules/memfs/lib/volume.js (volume.js:29:14)
    at __require (chunk-VX4GZB4L.js?v=167728fa:3:50)
    at ../../node_modules/memfs/lib/index.js (index.js:17:16)
    at __require (chunk-VX4GZB4L.js?v=167728fa:3:50)
    at index.js:48:27
```

**Comment by abhishiv** [comment]
Fixed by doing 

```
npm install events util path
```

Although I wish there was a version of memfs which wasn't so heavy.

**Comment by G-Rath** [comment]
There's not really anyway to avoid those dependences or prevent that erroring - if we were to specify them as explicit dependencies then on Node we would be installing more dependencies for functionality that node natively provides.

We are working on a v4 which changes the build target to at least es6 whichll make things a bit lighter
