### ISSUE TITLE
Errors working with certain path names

### ISSUE THREAD

**Issue by dmurvihill** [streamich/memfs#938]
Implement the following test (written in TS/Jest; not sure what your stack looks like but it shouldn't be too hard to adapt):

```typescript
it('should allow directories named __proto__', async () => {
  const dirName = '/__proto__';
  expect(await dirExists(dirName)).toBe(false);
  await memfs.fs.promises.mkdir(dirName);
  try {
    expect(await dirExists(dirName)).toBe(true);
  } finally {
    await memfs.fs.promises.rmdir(dirName);
  }
});

function dirExists(path: string): Promise<boolean> {
  return memfs.fs.promises
    .access(path, memfs.fs.promises.constants.R_OK)
    .then(() => true)
    .catch(() => false);
}
```

Result:
```
Error: ENOENT: no such file or directory, rmdir '/__proto__'

    at createError (C:\Users\d\IdeaProjects\big-shuffle\node_modules\memfs\src\node\util.ts:138:17)
    at Volume.getLinkOrThrow (C:\Users\d\IdeaProjects\big-shuffle\node_modules\memfs\src\volume.ts:404:33)
    at Volume.getLinkAsDirOrThrow (C:\Users\d\IdeaProjects\big-shuffle\node_modules\memfs\src\volume.ts:453:23)
    at Volume.rmdirBase (C:\Users\d\IdeaProjects\big-shuffle\node_modules\memfs\src\volume.ts:1628:23)
    at Immediate.<anonymous> (C:\Users\d\IdeaProjects\big-shuffle\node_modules\memfs\src\volume.ts:516:25)
    at processImmediate (node:internal/timers:478:21)
```

The analogous test on the real `fs/promises` is passing.

This was only tested with `/__proto__` as the directory name, but there may be other affected names and functions.

Thanks to [fast-check](https://github.com/dubzzz/fast-check) for finding this bug.

**Comment by G-Rath** [comment]
I expect `__proto__` is probably the only one, and it'll be because we're using a plain object to track the filesystem which ignores assignments to `__proto__`.

It might just be a matter of using `Object.create(null)` instead of `{}` 🤔
